version: '3.8'

services:
  app:
    image: secultceara/api-email:latest
    container_name: api-email-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: ["supervisord", "-c", "/etc/supervisord.conf"]
    networks:
      - api-network
      - lab

  nginx:
    image: nginx:alpine
    container_name: api-email-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80" 
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - api-network

  db:
    image: postgres:15
    container_name: api-email-db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE:-api_email}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-12345678}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - api-network
      

  redis:
    image: redis:alpine
    container_name: api-email-redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
  lab:
    external: true
    
volumes:
  app_data:
  dbdata: